name: Test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    strategy:
      matrix:
        include:
        - os: ubuntu-latest
          platform: linux
          arch: x64
        - os: macos-latest
          platform: darwin
          arch: arm64
        - os: windows-latest
          platform: win32
          arch: x64
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.platform }}-${{ matrix.arch }}
    steps:
    - if: ${{ matrix.platform == 'linux' }}
      run: |
        sudo apt update
        sudo apt install -y libgtk-4-dev
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - uses: actions/cache@v4
      with:
        path: vendor/libappling/vendor/bare/corestore
        key: corestore-${{ matrix.platform }}-${{ matrix.arch }}
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - run: npm install -g bare-dev
    - run: bare-dev configure --debug --platform ${{ matrix.platform }} --arch ${{ matrix.arch }}
    - run: bare-dev build --debug
